// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2V-MiL59pZZ9T-tNOdRGdKhoP9HamMo',
    appId: '1:436654453902:web:e09fcab7176da85e8f85df',
    messagingSenderId: '436654453902',
    projectId: 'birumanchu',
    authDomain: 'birumanchu.firebaseapp.com',
    storageBucket: 'birumanchu.appspot.com',
    measurementId: 'G-PF9V4VM2MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDsp_hdRqNLKBNk9m32cHrXXAkIHPxmQ8',
    appId: '1:436654453902:android:e66ea19cfeae19f88f85df',
    messagingSenderId: '436654453902',
    projectId: 'birumanchu',
    storageBucket: 'birumanchu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAn-qBxQkC-lIM1DETRfpI0AIJaYCKH60',
    appId: '1:436654453902:ios:07ebc02e205e3eeb8f85df',
    messagingSenderId: '436654453902',
    projectId: 'birumanchu',
    storageBucket: 'birumanchu.appspot.com',
    iosBundleId: 'com.example.group9Birumanchu',
  );
}
